-- =============================================================
-- SEEDS: 12 categorías (normalizadas), 100 marcas, 200 nombres de productos
-- Además: tabla tmp_nombres_producto y ejemplo de inserción a producto usando esos nombres
-- =============================================================
USE producto_barras;

-- Categorías (INSERT IGNORE por si ya existen)
INSERT IGNORE INTO categoria (nombre, descripcion) VALUES
 ('Bebidas','Líquidos y refrescos'),
 ('Lácteos','Leche, yogures, quesos'),
 ('Higiene','Cuidado personal'),
 ('Pastas','Secas y frescas'),
 ('Carnes','Vacuna, cerdo y pollo'),
 ('Frutas','Frescas y secas'),
 ('Verduras','Hortalizas y vegetales'),
 ('Pescados','De mar y río'),
 ('Panificación','Pan, facturas y galletas'),
 ('Limpieza','Hogar y multisuperficie'),
 ('Perfumería','Fragancias y cosmética'),
 ('Electrodomésticos','Pequeños y grandes electro');

-- 100 Marcas (INSERT IGNORE)
INSERT IGNORE INTO marca (nombre) VALUES
 ('Alborclean'),
 ('Albormont'),
 ('Alborplus'),
 ('Albortron'),
 ('Alborvia'),
 ('Altairdia'),
 ('Andechem'),
 ('Andepro'),
 ('Andera'),
 ('Argenpro'),
 ('Artemfer'),
 ('Artemmont'),
 ('Artempro'),
 ('Astraone'),
 ('Astrasense'),
 ('Atlantimax'),
 ('Aurelux'),
 ('Aurematic'),
 ('Aurera'),
 ('Aurorla'),
 ('Aurormax'),
 ('Aurorplus'),
 ('Boreallabs'),
 ('Borealta'),
 ('Borealtron'),
 ('Borematic'),
 ('Camptek'),
 ('Campwell'),
 ('Celola'),
 ('Celomax'),
 ('Celotronics'),
 ('Cobalfer'),
 ('Coballinea'),
 ('Cobalnis'),
 ('Dracotronics'),
 ('Equiclean'),
 ('Equicore'),
 ('Estelta'),
 ('Fjordco'),
 ('Fjordfresh'),
 ('Galaxco'),
 ('Galaxlog'),
 ('Heliopet'),
 ('Heliowood'),
 ('Hyperwood'),
 ('Icarta'),
 ('Icarvia'),
 ('Lumilite'),
 ('Lumimont'),
 ('Lumione'),
 ('Lumivia'),
 ('Magnahome'),
 ('Meridclean'),
 ('Meridware'),
 ('Nacarfer'),
 ('Nacartron'),
 ('Nacartronics'),
 ('Nimbusfresh'),
 ('Nimbusprime'),
 ('Novapro'),
 ('Omegachem'),
 ('Omegaone'),
 ('Omegatek'),
 ('Omegatronics'),
 ('Orbicore'),
 ('Orbifer'),
 ('Orbilab'),
 ('Orbisense'),
 ('Orbivy'),
 ('Orionfer'),
 ('Orionsense'),
 ('Pacifitek'),
 ('Patafresh'),
 ('Patamax'),
 ('Patana'),
 ('Patanis'),
 ('Patavy'),
 ('Polarprime'),
 ('Quimedia'),
 ('Quimeline'),
 ('Silvala'),
 ('Terracore'),
 ('Terraplex'),
 ('Tridentcore'),
 ('Turmana'),
 ('Vectordia'),
 ('Vectorpet'),
 ('Vectorprime'),
 ('Vitaplex'),
 ('Vitata'),
 ('Voltacore'),
 ('Voltala'),
 ('Voltalab'),
 ('Voltamatic'),
 ('Voltasol'),
 ('Zenitgen'),
 ('Zenitware'),
 ('Zentronics'),
 ('Zettaplex'),
 ('Zettatek');

-- Tabla auxiliar de nombres de producto
CREATE TABLE IF NOT EXISTS tmp_nombres_producto (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(120) NOT NULL,
  CONSTRAINT uq_tmp_nombre UNIQUE (nombre)
) ENGINE=InnoDB;

INSERT IGNORE INTO tmp_nombres_producto (nombre) VALUES
 ('Niebla Select Zero'),
 ('Andes Original Silvestre'),
 ('Pradera Integral Doble'),
 ('Pradera Premium Premium'),
 ('Río Premium Bajo Sodio'),
 ('Río Tradicional Andino'),
 ('Patagonia Artesanal Eco'),
 ('Sendero Gourmet Avena'),
 ('Sol Mediterráneo Mediterráneo'),
 ('Viñedo Integral Intenso'),
 ('Niebla Intenso Liviano'),
 ('Sierra Silvestre Del Campo'),
 ('Altamar Activo Nativo'),
 ('Luna Original Ligth'),
 ('Bosque Tradicional Tropical'),
 ('Valle Intenso Campo'),
 ('Sendero Ligth Especial'),
 ('Estrella Familiar Intenso'),
 ('Arroyo Activo Especial'),
 ('Pampas Campestre Cremoso'),
 ('Pradera Cremoso Sin Azúcar'),
 ('Arena Esencial Amanecer'),
 ('Cascada Silvestre Andino'),
 ('Jarilla Refinado Patagónico'),
 ('Niebla Intenso Avena'),
 ('Andes Familiar Hierbas'),
 ('Campo Tropical Bajo Sodio'),
 ('Sendero Refinado Especias'),
 ('Patagonia Liviano Integral'),
 ('Cascada Andino Vainilla'),
 ('Laguna Liviano Gran Reserva'),
 ('Viñedo Serrano Criollo'),
 ('Bahía Clásico Criollo'),
 ('Andes Puro Tropical'),
 ('Sierra Select Ligth'),
 ('Altamar Selecto Especias'),
 ('Pampas Selecto Avena'),
 ('Trigal Cremoso Especias'),
 ('Totoral Especial Atardecer'),
 ('Monte Intenso Limón'),
 ('Pampas Cremoso Puro'),
 ('Cascada Extra Especias'),
 ('Campo Esencial Doble'),
 ('Sierra Fresco Ligth'),
 ('Pradera Extra Amanecer'),
 ('Bosque Mediterráneo De Autor'),
 ('Quebrada Andino Intenso'),
 ('Arroyo Natural Mediterráneo'),
 ('Bahía Silvestre Artesanal'),
 ('Rocío Premium Puro'),
 ('Rocío Intenso Campestre'),
 ('Cardonal Tradicional Selección'),
 ('Totoral Esencial Campestre'),
 ('Patagonia Campestre Sin Azúcar'),
 ('Pradera Integral Campestre'),
 ('Cumbre Vital Atardecer'),
 ('Cascada Premium Especias'),
 ('Quebrada Criollo Criollo'),
 ('Océano Criollo Ligth'),
 ('Manantial Suave Clásico'),
 ('Cardonal Vital Atardecer'),
 ('Puerto Criollo Gourmet'),
 ('Altamar Gourmet Natural'),
 ('Huerta Liviano Silvestre'),
 ('Laguna Silvestre Amanecer'),
 ('Trébol Silvestre Atardecer'),
 ('Trigal Suave Integral'),
 ('Totoral Ligth Ligth'),
 ('Trébol Silvestre Amanecer'),
 ('Océano Noble Criollo'),
 ('Sol Selecto Limón'),
 ('Totoral Vital Vital'),
 ('Bahía Activo Vainilla'),
 ('Huerta Fresco Selección'),
 ('Niebla Ligero Especial'),
 ('Pehuén Original Criollo'),
 ('Cumbre Familiar Especias'),
 ('Río Campestre Bajo Sodio'),
 ('Trigal Tradicional Original'),
 ('Cumbre Campestre Natural'),
 ('Aurora Nativo Silvestre'),
 ('Rocío Campestre Andino'),
 ('Trigal Nativo Nocturno'),
 ('Río Deluxe De Autor'),
 ('Trigal Familiar Silvestre'),
 ('Totoral Activo Serrano'),
 ('Trébol Deluxe Ligero'),
 ('Cardonal Mediterráneo Atardecer'),
 ('Puerto Liviano Natural'),
 ('Manantial Fresco Gourmet'),
 ('Andes Refinado Campestre'),
 ('Laguna Clásico Especias'),
 ('Altamar Activo Doble'),
 ('Brisa Tropical Criollo'),
 ('Sendero Tradicional Mediterráneo'),
 ('Horizonte Ligero Silvestre'),
 ('Brisa Refinado Especias'),
 ('Sendero Noble Suave'),
 ('Manantial Serrano Intenso'),
 ('Río Silvestre Tropical'),
 ('Pampa Ligth Tradición'),
 ('Pampa Esencial Amanecer'),
 ('Cumbre Andino Suave'),
 ('Manantial Dorado Cacao'),
 ('Brisa Mediterráneo Especial'),
 ('Niebla Extra Familiar'),
 ('Cascada Criollo Naranja'),
 ('Brisa Selecto Naranja'),
 ('Sol Ligth Tropical'),
 ('Pinar Supremo Patagónico'),
 ('Jarilla Campestre Silvestre'),
 ('Campo Artesanal Premium'),
 ('Luna Esencial Eco'),
 ('Río Vital Sin Azúcar'),
 ('Jarilla Criollo Patagónico'),
 ('Quebrada Criollo Hierbas'),
 ('Pampa Premium Patagónico'),
 ('Viñedo Natural Campo'),
 ('Puerto Reserva Selección'),
 ('Estrella Selecto Campo'),
 ('Brisa Nativo Original'),
 ('Pampas Tradicional Criollo'),
 ('Quebrada Artesanal Campo'),
 ('Sol Esencial Selección'),
 ('Río Especial Tropical'),
 ('Manantial Andino Del Campo'),
 ('Aurora Nativo Integral'),
 ('Cumbre Refinado Criollo'),
 ('Pampas Tropical Especial'),
 ('Pampas Artesanal Natural'),
 ('Trébol Tradicional Puro'),
 ('Cardonal Extra Tropical'),
 ('Estrella Activo Doble'),
 ('Océano Premium Naranja'),
 ('Jarilla Integral Cacao'),
 ('Pinar Liviano Patagónico'),
 ('Puerto Artesanal Andino'),
 ('Quebrada Esencial Zero'),
 ('Pampas Deluxe Clásico'),
 ('Cascada Patagónico Especias'),
 ('Estrella Original Especias'),
 ('Manantial Activo Campestre'),
 ('Arroyo Especial Avena'),
 ('Pehuén Integral Proteico'),
 ('Huerta Noble Premium'),
 ('Patagonia Activo Fusión'),
 ('Niebla Clásico Original'),
 ('Cardonal Cremoso Puro'),
 ('Trébol Andino Fresco'),
 ('Sol Clásico Premium'),
 ('Río Fresco Avena'),
 ('Rocío Activo Criollo'),
 ('Huerta Mediterráneo Vital'),
 ('Sierra Reserva Silvestre'),
 ('Bosque Extra Campestre'),
 ('Andes Campestre Atardecer'),
 ('Pradera Especial Campestre'),
 ('Río Original Amanecer'),
 ('Pampa Vital Cremoso'),
 ('Andes Criollo Gran Reserva'),
 ('Horizonte Original Cacao'),
 ('Océano Integral Natural'),
 ('Altamar Reserva Campo'),
 ('Cardonal Natural Patagónico'),
 ('Laguna Ligero Clásico'),
 ('Totoral Puro Selección'),
 ('Laguna Especial Gourmet'),
 ('Huerta Criollo Vital'),
 ('Bahía Criollo Fresco'),
 ('Luna Artesanal Andino'),
 ('Estrella Balanceado Doble'),
 ('Estrella Tradicional De Autor'),
 ('Valle Vital Zero'),
 ('Río Noble Especias'),
 ('Totoral Criollo Cremoso'),
 ('Huerta Refinado Criollo'),
 ('Estrella Dorado Proteico'),
 ('Brisa Tradicional Tropical'),
 ('Arroyo Natural Tropical'),
 ('Horizonte Intenso Atardecer'),
 ('Pampa Liviano Nativo'),
 ('Pradera Mediterráneo Andino'),
 ('Monte Silvestre Original'),
 ('Pampa Clásico Campestre'),
 ('Bosque Serrano Bajo Sodio'),
 ('Viñedo Nativo Naranja'),
 ('Trigal Suave Nocturno'),
 ('Jarilla Liviano Campestre'),
 ('Patagonia Clásico Eco'),
 ('Niebla Premium Fusión'),
 ('Patagonia Nativo Andino'),
 ('Quebrada Esencial Sin Azúcar'),
 ('Viñedo Noble Selección'),
 ('Bosque Tropical Tropical'),
 ('Arroyo Tradicional De Autor'),
 ('Río Patagónico Original'),
 ('Rocío Patagónico Zero'),
 ('Rocío Activo Puro'),
 ('Cumbre Puro Proteico'),
 ('Arena Andino Fusión');

-- Ejemplo de creación de productos a partir de tmp_nombres_producto (distribuye categorías y marcas reales)
SET @count_c := (SELECT COUNT(*) FROM categoria);
SET @count_m := (SELECT COUNT(*) FROM marca);

INSERT INTO producto (nombre, categoria_id, marca_id, precio, costo, stock, fecha_alta)
WITH RN AS (
  SELECT ROW_NUMBER() OVER (ORDER BY id) AS rn, nombre FROM tmp_nombres_producto
),
cat AS (SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn FROM categoria),
mar AS (SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn FROM marca)
SELECT
  r.nombre,
  c.id AS categoria_id,
  m.id AS marca_id,
  -- precios: costo [100..900), margen [0..500)
  ROUND(100 + RAND(r.rn) * 800, 2) + ROUND(RAND(r.rn*7) * 500, 2) AS precio,
  ROUND(100 + RAND(r.rn) * 800, 2) AS costo,
  FLOOR(RAND(r.rn*13) * 200) AS stock,
  DATE_ADD(DATE('2023-01-01'), INTERVAL FLOOR(RAND(r.rn*101) * 1000) DAY) AS fecha_alta
FROM RN r
JOIN cat c ON c.rn = 1 + MOD(r.rn*19, @count_c)
JOIN mar m ON m.rn = 1 + MOD(r.rn*29, @count_m);

-- Códigos de barras 1→1 para los nuevos productos
INSERT INTO codigo_barras (producto_id, gtin13, tipo, activo)
SELECT p.id, CONCAT('779', LPAD(p.id, 10, '0')), 'EAN13', 1
FROM producto p
LEFT JOIN codigo_barras cb ON cb.producto_id = p.id
WHERE p.nombre IN (SELECT nombre FROM tmp_nombres_producto)
  AND cb.producto_id IS NULL;